### ISSUE TITLE
model.load_weights(modelweights)报错

### ISSUE THREAD

**Issue by GitForMrJiu** [TombRaiderjf/cyg#1]
model.load_weights(modelweights)报错
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by node bidirectional/CudnnRNN (defined at F:/workspace/server.py:63) with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="gru", seed2=0, is_training=true]
Registered devices: [CPU]
Registered kernels:
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]

**Comment by zhangJache** [comment]
> model.load_weights(modelweights)报错
> tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by node bidirectional/CudnnRNN (defined at F:/workspace/server.py:63) with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="gru", seed2=0, is_training=true]
> Registered devices: [CPU]
> Registered kernels:
> device='GPU'; T in [DT_HALF]
> device='GPU'; T in [DT_FLOAT]
> device='GPU'; T in [DT_DOUBLE]

你好 请问这个解决了吗
